version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - '9200:9200'
    environment:
      discovery.type: 'single-node'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - workshop_net
  cerebro:
    image: yannart/cerebro:0.8.1
    ports:
      - '9000:9000'
    networks:
      - workshop_net
networks:
  workshop_net:
    driver: bridge
volumes:
  esdata:
    driver: local
